version: '3'
services:
  mysql:
    image: mysql:8
    container_name: sequelize-course-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-mysql}
      MYSQL_USER: ${DB_USERNAME:-mysql}
      MYSQL_PASSWORD: ${DB_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-mysql}
    ports:
      - ${DB_PORT:-3306}:3306
  mysql-test:
    image: mysql:8
    container_name: sequelize-course-test-db
    environment:
      MYSQL_DATABASE: ${DB_TEST_DATABASE:-mysql}
      MYSQL_USER: ${DB_TEST_USERNAME:-mysql}
      MYSQL_PASSWORD: ${DB_TEST_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${DB_TEST_PASSWORD:-mysql}
    ports:
      - ${DB_TEST_PORT:-3307}:3306
